dataSource:
    pooled: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: church_services_user
    password: church_services_password
    dbCreate: update
    url: jdbc:postgresql://db:5432/postgres
    properties:
        hibernate.default_schema: public

grails:
    cors:
        enabled: true
        mappings:
            '/**':
                allowedOrigins: ['http://localhost:4200']
                allowedMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
                allowedHeaders: ['*']
                exposedHeaders: ['*']
                allowCredentials: true
                maxAge: 3600

spring:
    groovy:
        template:
            check-template-location: false